spring:
  profiles:
    active: prod
person:
  firstName: newName
---
spring:
  profiles: dev
server:
  port: 5555

person:
  lastName: ${random.uuid} # uuid
  age: ${random.int(100)} # 0-100的随机值
  male: true
  birth: 1985/03/03
  maps: {k1: v1, k2: 20, k3: true}
  lists:
    - lisi
    - wangwu
  dog:
    name: ${person.firstName:无名}_小黄dev #如果为空, 取默认值
    age: ${random.int[1,3]} #10-20之间的随机值: 中间还不能有空格, 实测!
---
spring:
  profiles: prod
server:
  port: 6666

person:
  lastName: ${random.uuid} # uuid
  age: ${random.int(100)} # 0-100的随机值
  male: true
  birth: 1985/03/03
  maps: {k1: v1, k2: 20, k3: true}
  lists:
    - lisi
    - wangwu
  dog:
    name: ${person.firstName:无名}_小黄prod #如果为空, 取默认值
    age: ${random.int[4,6]} #10-20之间的随机值: 中间还不能有空格, 实测!
